# Generated by Django 2.2.7 on 2019-11-07 15:08

import aswissues.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aswissues', '0002_auto_20191107_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='prioritat',
            field=models.CharField(choices=[('Trivial', 'Trivial'), ('Menor', 'Menor'), ('Major', 'Major'), ('Critica', 'Crítica'), ('Bloquejant', 'Bloquejant')], default=aswissues.enums.PrioritatSelector('Trivial'), max_length=15),
        ),
    ]
