# Generated by Django 2.2.6 on 2019-11-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aswissues', '0003_auto_20191107_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='adjunt',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
