# Generated by Django 2.2.7 on 2019-11-14 14:33

import aswissues.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aswissues', '0004_auto_20191114_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='prioritat',
            field=models.CharField(choices=[('Trivial', 'Trivial'), ('Menor', 'Menor'), ('Major', 'Major'), ('Critica', 'Crítica'), ('Bloquejant', 'Bloquejant')], default=aswissues.enums.PrioritatSelector('Trivial'), max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tipus',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Millora', 'Millora'), ('Proposta', 'Proposta'), ('Tasca', 'Tasca')], default=aswissues.enums.TipusSelector('Millora'), max_length=20),
        ),
    ]
