# Generated by Django 2.2.6 on 2019-11-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aswissues', '0004_issue_adjunt'),
        ('aswissues', '0004_auto_20191114_1330'),
    ]

    operations = [
    ]
