# Generated by Django 2.0.5 on 2019-11-19 19:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aswissues', '0006_auto_20191114_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='data_creacio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aswissues.User'),
            preserve_default=False,
        ),
    ]
