# Generated by Django 2.2.7 on 2019-11-19 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aswissues', '0007_auto_20191119_1921'),
        ('aswissues', '0005_auto_20191114_1433'),
    ]

    operations = [
    ]
