# Generated by Django 2.2.6 on 2019-11-19 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aswissues', '0007_auto_20191119_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='adjunt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aswissues.Attachment'),
            preserve_default=False,
        ),
    ]
