# Generated by Django 2.2.6 on 2019-11-19 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aswissues', '0008_comment_adjunt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='adjunt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aswissues.Attachment'),
        ),
    ]
