# Generated by Django 2.2.7 on 2019-11-19 21:25

import aswissues.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aswissues', '0008_merge_20191119_2121'),
    ]

    operations = []
