# Generated by Django 2.2.7 on 2019-11-19 21:25

import aswissues.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aswissues', '0008_merge_20191119_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Nou', 'Nou'), ('Obert', 'Obert'), ('Resolt', 'Resolt'), ('Espera', 'En Espera'), ('Invalit', 'Invalit'), ('Duplicat', 'Duplicat'), ('NoFix', 'No fix'), ('Tancat', 'Tancat')], default=aswissues.enums.StatusSelector('Obert'), max_length=20),
        ),
    ]
