# Generated by Django 2.2.7 on 2019-11-19 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aswissues', '0010_issue_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='watchers',
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aswissues.Issue')),
                ('watcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aswissues.User')),
            ],
        ),
    ]
