# Generated by Django 2.2.7 on 2019-11-19 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aswissues', '0011_auto_20191119_2203'),
        ('aswissues', '0009_issue_status'),
    ]

    operations = [
    ]
