# Generated by Django 2.2.7 on 2019-12-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aswissues', '0016_auto_20191120_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='data_creacio',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='type',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='watch',
            name='type',
            field=models.BooleanField(null=True),
        ),
    ]
